// Arrange Alphabetically
// Locators for QA Playground - Forms Page
const FormsLocators = {
    aboutYouInput:
        '[id="bio"]',
    accountResetButton:
        '[data-testid="reset-form-btn"]',
    accountResult:
        '[data-testid="form-success-msg"]',
    accountPasswordInput:
        '[data-testid="input-password"]',
    accountSection:
        '[data-testid="form-account-setup"]',
    addressResetButton:
        '[data-testid="btn-address-reset"]',
    addressResult:
        '[data-testid="result-address"]',
    addressSection:
        '[data-testid="form-address"]',
    appiumCheckBox:
        '[data-testid="checkbox-interest-appium"]',
    cityError:
        '[data-testid="error-city"]',
    cityInput:
        '[data-testid="input-city"]',
    confirmPasswordError:
        '[data-testid="error-confirm-password"]',
    confirmPasswordInput:
        '[data-testid="input-confirm-password"]',
    countryDropdown:
        '[data-testid="select-country"]',
    countryError:
        '[data-testid="error-country"]',
    cypressCheckBox:
        '[data-testid="checkbox-interest-cypress"]',
    dateOfBirthError:
        '[data-testid="error-dob"]',
    dateOfBirthInput:
        '[data-testid="input-dob"]',
    emailInput:
        '[data-testid="input-login-email"]',
    femaleRadioButton:
        '[data-testid="radio-gender-female"]',
    fillAgainButton:
        '[data-testid="btn-fill-again"]',
    firstNameError:
        '[data-testid="error-first-name"]',
    firstNameInput:
        '[data-testid="input-first-name"]',
    genderError:
        '[data-testid="error-gender"]',
    interestsError:
        'p[role="alert"]',
    interestResetButton:
        '[data-testid="btn-interests-reset"]',
    interestsResult:
        '[data-testid="result-interests"]',
    interestsSection:
        '[data-testid="form-interests"]',
    jestCheckBox:
        '[data-testid="checkbox-interest-jest"]',
    lastNameError:
        '[data-testid="error-last-name"]',
    lastNameInput:
        '[data-testid="input-last-name"]',
    loginButton:
        '[data-testid="btn-login-submit"]',
    loginEmailError:
        '[data-testid="error-login-email"]',
    loginPasswordError:
        '[data-testid="error-login-password"]',
    loginPasswordInput:
        '[id="login-password"]',
    loginResetButton:
        '[data-testid="btn-login-reset"]',
    loginResult:
        '[data-testid="result-login"]',
    loginSection:
        '[data-testid="form-login"]',
    maleRadioButton:
        '[data-testid="radio-gender-male"]',
    otherRadioButton:
        '[data-testid="radio-gender-other"]',
    passwordError:
        '[data-testid="error-password"]',
    personalResetButton:
        '[data-testid="btn-personal-reset"]',
    personalResult:
        '[data-testid="result-personal"]',
    personalSection:
        '[data-testid="form-personal"]',
    phoneError:
        '[data-testid="error-phone"]',
    phoneInput:
        '[data-testid="input-phone"]',
    playwrightCheckBox:
        '[data-testid="checkbox-interest-playwright"]',
    saveAddressButton:
        '[data-testid="btn-address-submit"]',
    saveDetailsButton:
        '[data-testid="btn-personal-submit"]',
    saveInterestButton:
        '[data-testid="btn-interests-submit"]',
    seleniumCheckBox:
        '[data-testid="checkbox-interest-selenium"]',
    submitButton:
        '[data-testid="submit-form-btn"]',
    termsAndConditionCheckBox:
        '[data-testid="checkbox-terms"]',
    termsAndConditionError:
        '[id="termsError"]'
};

module.exports = { FormsLocators };