name: Auto Merge PR

on:
  workflow_dispatch:

  workflow_run:
    workflows:
      - Playwright Tests - PR or Manual Validation
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug PR
        run: |
          echo "PR Data:"
          echo '${{ toJson(github.event.workflow_run.pull_requests) }}'