name: Auto Merge PR

on:
  workflow_dispatch:

  workflow_run:
    workflows:
      - Playwright Tests - PR or Manual Validation
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Show PR
        run: |
          echo '${{ toJson(github.event.workflow_run.pull_requests) }}'

      - name: Merge PR
        run: |
          gh pr merge \
            ${{ github.event.workflow_run.pull_requests[0].number }} \
            --repo ${{ github.repository }} \
            --squash \
            --delete-branch
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}