name: Slack Notifications for Github Actions

on:
  workflow_run:
    workflows:
      - Playwright Tests
    types:
      - completed

  release:
    types:
      - published

jobs:
  test-success:
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "✅ Playwright tests passed"
            }

  test-failure:
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest

    steps:
      - uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "❌ Playwright tests failed"
            }

  release-notification:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "🚀 New Release: ${{ github.event.release.tag_name }}"
            }